trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: AzureCLI@1
  displayName: 'Install the CLI'
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptLocation: inlineScript
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@1
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptLocation: inlineScript
    inlineScript: 'az ml folder attach -w kaoriAzureML -g kaori.nawataRG'

- task: AzureCLI@1
  displayName: 'Submit script run'
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptLocation: inlineScript
    inlineScript: 'az ml run submit-script -c sklearn -e test -d myenv.yml train.py'

- task: AzureCLI@1
  displayName: 'Register model'
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptLocation: inlineScript
    inlineScript: 'az ml model register -n mymodel -p sklearn_regression_model.pkl -t model.json'

- task: AzureCLI@1
  displayName: 'Deploy model'
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptLocation: inlineScript
    inlineScript: 'az ml model deploy -n acicicd -f model.json --ic inferenceConfig.yml --dc deploymentConfig.yml --overwrite'

- task: AzureCLI@1
  displayName: 'Delete deployed service'
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptLocation: inlineScript
    inlineScript: 'az ml service delete -n acicicd'

- task: AzureCLI@1
  displayName: 'IoTHub Setting'
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    scriptLocation: 'inlineScript'
    inlineScript: |
      iot_hub_name="kaoriAzureML"
      iot_device_id="EdgeVM"
      az iot edge set-modules --device-id $iot_device_id --hub-name $iot_hub_name --content deployment.json

